### ISSUE TITLE
"babel-preset-xxxx" для babelify

### ISSUE THREAD

**Issue by NightDiRaven** [mrTimofey/node-frontend-platform#6]
Смотри, у тебя в пакете фронтизера сейчас при установкие "babel-preset-latest" для babelify команды по умолчанию (Вообще ещё с сентября, но не суть), но там, насколько я понимаю, обычный импорт (А может и ещё что-то помимо этого), например 
` import {Core} from './core/core.es6' `
где в коре лежит 
`
export class Core {
test(){
console.log('test');
}
}
` 
не работает, потому что сейчас это выбрасывает ошибку мол 
`"'import' and 'export' may appear only with 'sourceType: module'"`. 
Ну и это все ломает, если не сменить на babel-preset-es2015 как это было раньше. Там есть в config.js дополнительные параметры browserifyArgs, но они конкатенируются с helpers.browserifyArgs в которых уже прописаны все параметры, поэтому не заменить, разве что лезть в фронтизер глобально установленный и менять там в helpers файле helpers.browserifyArgs и прописывать es2015 чтобы сменить этот параметр. Если я все правильно понимаю, а это не очень, ну это скорее как энчантмент, и в какой-то мере РЕГРЕСС, но без этого у фронитизера нет обратной совместимости... 

Если бы в config.js была возможность указывать эти параметры, было бы удобно

**Comment by mrTimofey** [comment]
Я убрал поддержку расширения файлов es6. Попробуй просто везде переименовать их в js, и по идее всё заработает.

**Comment by NightDiRaven** [comment]
Это было слишком давно да и все работает же
